# Generated by Django 5.0.6 on 2024-05-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_total_alter_order_status_alter_tovar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartOrder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart'),
        ),
    ]
