# Generated by Django 5.0.6 on 2024-05-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartOrder',
        ),
    ]
